<?php

require_once dirname(__FILE__) . '/../../../../../library/_backup/Zend/Exception.php';

/**
 * Test class for Zend_Exception.
 * Generated by PHPUnit on 2011-07-02 at 16:22:04.
 */
class Zend_ExceptionTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Zend_Exception
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
	$this->object = new Zend_Exception;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
	
    }

    /**
     * @todo Implement test__call().
     */
    public function test__call() {
	// Remove the following lines when you implement this test.
	$this->markTestIncomplete(
		'This test has not been implemented yet.'
	);
    }

    /**
     * @todo Implement test__toString().
     */
    public function test__toString() {
	// Remove the following lines when you implement this test.
	$this->markTestIncomplete(
		'This test has not been implemented yet.'
	);
    }

}

?>
